### ISSUE TITLE
Running USBIPManager.py throws TypeError: create_task() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by Tuararo** [lompal/USBIPManager#3]
Hi lompal,

I am trying to run USBIPManager.py in a Windows 10 Pro, but the following output is got:

![USBIPManagerError](https://user-images.githubusercontent.com/71127589/92917763-0f90a780-f42f-11ea-8bb2-fe76218c39a7.jpg)

Maybe I am missing something. 

Thank you.

**Comment by m-antonov** [comment]
Hi @Tuararo,

What version of Python are you using?
The latest update assumes that you are using Python 3.8 or later, so I think you are using a lower version.
Try a more recent one.

**Comment by Tuararo** [comment]
Hi @lompal,

You were right. I was running an older Python version implemented in Visual Studio 2019. Installing standalone Python 3.8 solved the problem.

Thank you very much.
